// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmVzoOw-eG8l1Sl6Cd2N12DYf6PXohlo',
    appId: '1:708676081532:web:f295f607184e34f931f6f9',
    messagingSenderId: '708676081532',
    projectId: 'diet-plan-d86cd',
    authDomain: 'diet-plan-d86cd.firebaseapp.com',
    storageBucket: 'diet-plan-d86cd.firebasestorage.app',
    measurementId: 'G-D1Q5RTLHXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoxXM3a-BoYFuGsVLGWZpbJkLhOsGt34U',
    appId: '1:708676081532:android:34edac8445f0735631f6f9',
    messagingSenderId: '708676081532',
    projectId: 'diet-plan-d86cd',
    storageBucket: 'diet-plan-d86cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjvpSvioY0d67OLYKKqP0ls8VD_GX4-t4',
    appId: '1:708676081532:ios:ea78c876764ed0e031f6f9',
    messagingSenderId: '708676081532',
    projectId: 'diet-plan-d86cd',
    storageBucket: 'diet-plan-d86cd.firebasestorage.app',
    androidClientId: '708676081532-d61tp4nh1i5hmeh0qsm1nmtjeakrm8g2.apps.googleusercontent.com',
    iosClientId: '708676081532-kqdkte7os2co1d6pd8s2jm6hkhsf2mlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietPlanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjvpSvioY0d67OLYKKqP0ls8VD_GX4-t4',
    appId: '1:708676081532:ios:ea78c876764ed0e031f6f9',
    messagingSenderId: '708676081532',
    projectId: 'diet-plan-d86cd',
    storageBucket: 'diet-plan-d86cd.firebasestorage.app',
    androidClientId: '708676081532-d61tp4nh1i5hmeh0qsm1nmtjeakrm8g2.apps.googleusercontent.com',
    iosClientId: '708676081532-kqdkte7os2co1d6pd8s2jm6hkhsf2mlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietPlanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtmVzoOw-eG8l1Sl6Cd2N12DYf6PXohlo',
    appId: '1:708676081532:web:7a85e420cdf9b62531f6f9',
    messagingSenderId: '708676081532',
    projectId: 'diet-plan-d86cd',
    authDomain: 'diet-plan-d86cd.firebaseapp.com',
    storageBucket: 'diet-plan-d86cd.firebasestorage.app',
    measurementId: 'G-PYE1ZPC2FE',
  );

}